name: NameIT CI

on:
  push:
  pull_request:    
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-18.04, macos-latest]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run the scripts
        shell: pwsh
        run: ./ContinuousIntegration.ps1

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Check in results
          commit_user_name: "Pester check in"
